---
title: "Lab Exercise 1"
output: html_document
date: "2024-02-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


CATEGORY- PET SUPPLIES
FIRST PRODUCT- Cat Brushes

```{r}

library(rvest)
library(dplyr)
library(polite)
library(httr)


Pet_Supplies <- data.frame()

url <- "https://www.amazon.co.uk/s?k=cat+brush&crid=3UWMHMA8AJL0W&sprefix=cat+br%2Caps%2C402&ref=nb_sb_noss_2"

session <- bow(url,user_agent = "For Educational Purposes")

session

Category <- "PetSupplies"

catbrush <- scrape(session) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
catbrush48 <- catbrush[1:48]
catbrush48


catbrush_prices <- scrape(session) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
catbrush_prices48 <-catbrush_prices[1:48]
catbrush_prices48


catbrush_Ratings <- scrape(session) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
catbrush_Ratings48<-catbrush_Ratings[1:48]
catbrush_Ratings48


catbrush_noReviews <- scrape(session) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
catbrush_noReviews48<-catbrush_noReviews[1:48]
catbrush_noReviews48

Pet_Supplies <-data.frame(category = Category,
                               name = catbrush48,
                               price = catbrush_prices48,
                               ratings = catbrush_Ratings48,
                               no_of_reviews = catbrush_noReviews48)

url2 <- "https://www.amazon.co.uk/s?k=cat+brush&page=2&crid=3UWMHMA8AJL0W&qid=1708611991&sprefix=cat+br%2Caps%2C402&ref=sr_pg_2"
  
session2 <- bow(url2,user_agent = "For Educational Purposes")

session2

Category <- "PetSupplies"
  
  page2_catbrush <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page2_catbrush48 <- page2_catbrush[1:48]
page2_catbrush48


page2_catbrush_prices <- scrape(session2) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
page2_catbrush_prices48 <-page2_catbrush_prices[1:48]
page2_catbrush_prices48


page2_catbrush_Ratings <- scrape(session2) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page2_catbrush_Ratings48<-page2_catbrush_Ratings[1:48]
page2_catbrush_Ratings48


page2_catbrush_noReviews <- scrape(session2) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page2_catbrush_noReviews48<-page2_catbrush_noReviews[1:48]
page2_catbrush_noReviews48

Pet_Supplies <-rbind(Pet_Supplies,data.frame(category = Category,
                               name = page2_catbrush48,
                               price = page2_catbrush_prices48,
                               ratings = page2_catbrush_Ratings48,
                               no_of_reviews = page2_catbrush_noReviews48))
                     

url3 <-"https://www.amazon.co.uk/s?k=cat+brush&page=3&crid=3UWMHMA8AJL0W&qid=1708612119&sprefix=cat+br%2Caps%2C402&ref=sr_pg_3"

session3 <- bow(url3,user_agent = "For Educational Purposes")

amazon <- read_html(url)

Category <- "PetSupplies"
  
  page3_catbrush <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
page3_catbrush48 <- page3_catbrush[1:48]
page3_catbrush48


page3_catbrush_prices <- scrape(session3) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
page3_catbrush_prices48 <-page3_catbrush_prices[1:48]
page3_catbrush_prices48


page3_catbrush_Ratings <- scrape(session3) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
page3_catbrush_Ratings48<-page3_catbrush_Ratings[1:48]
page3_catbrush_Ratings48


page3_catbrush_noReviews <- scrape(session3) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
page3_catbrush_noReviews48<-page3_catbrush_noReviews[1:48]
page3_catbrush_noReviews48

Pet_Supplies <-rbind(Pet_Supplies,data.frame(category = Category,
                               name = page3_catbrush48,
                               price = page3_catbrush_prices48,
                               ratings = page3_catbrush_Ratings48,
                               no_of_reviews = page3_catbrush_noReviews48))
                     
Pet_Supplies <- Pet_Supplies[1:100,]


Pet_Supplies
                    
```



CATEGORY- PET SUPPLIES
SECOND PRODUCT- Cat Apparel


```{r}


Pet_Supplies <- data.frame()

url <- "https://www.amazon.co.uk/s?k=cat+apparel&crid=2K9MOR8O7SK02&sprefix=cat+apparel%2Caps%2C322&ref=nb_sb_noss_1"

session <- bow(url,user_agent = "For Educational Purposes")

session

Category <- "PetSupplies"

catapparel <- scrape(session) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
catapparel48 <- catapparel[1:48]
catapparel48


catapparel_prices <- scrape(session) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
catapparel_prices48 <-catapparel_prices[1:48]
catapparel_prices48


catapparel_Ratings <- scrape(session) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
catapparel_Ratings48<-catapparel_Ratings[1:48]
catapparel_Ratings48


catapparel_noReviews <- scrape(session) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
catapparel_noReviews48<-catapparel_noReviews[1:48]
catapparel_noReviews48

Pet_Supplies <-data.frame(category = Category,
                               name = catapparel48,
                               price = catapparel_prices48,
                               ratings = catapparel_Ratings48,
                               no_of_reviews = catapparel_noReviews48)

second_url <- "https://www.amazon.co.uk/s?k=cat+apparel&page=2&crid=2K9MOR8O7SK02&qid=1708612710&sprefix=cat+apparel%2Caps%2C322&ref=sr_pg_2"

session2 <- bow(second_url,user_agent = "For Educational Purposes")

session2

Category <- "PetSupplies"

catapparel <- scrape(session2) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
catapparel48 <- catapparel[1:48]
catapparel48


catapparel_prices <- scrape(session2) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
catapparel_prices48 <-catapparel_prices[1:48]
catapparel_prices48


catapparel_Ratings <- scrape(session2) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
catapparel_Ratings48<-catapparel_Ratings[1:48]
catapparel_Ratings48


catapparel_noReviews <- scrape(session2) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
catapparel_noReviews48<-catapparel_noReviews[1:48]
catapparel_noReviews48

Pet_Supplies <-rbind(Pet_Supplies,data.frame(category = Category,
                               name = catapparel48,
                               price = catapparel_prices48,
                               ratings = catapparel_Ratings48,
                               no_of_reviews = catapparel_noReviews48))

third_url <- "https://www.amazon.co.uk/s?k=cat+apparel&page=3&crid=2K9MOR8O7SK02&qid=1708612990&sprefix=cat+apparel%2Caps%2C322&ref=sr_pg_3"

session3 <- bow(third_url,user_agent = "For Educational Purposes")

session3

Category <- "PetSupplies"

catapparel <- scrape(session3) %>%
  html_nodes("span.a-text-normal") %>%
  html_text
catapparel48 <- catapparel[1:48]
catapparel48


catapparel_prices <- scrape(session3) %>%
  html_nodes("span.a-price-whole") %>%
  html_text
catapparel_prices48 <-catapparel_prices[1:48]
catapparel_prices48


catapparel_Ratings <- scrape(session3) %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4.aok-align-bottom") %>%
  html_text
catapparel_Ratings48<-catapparel_Ratings[1:48]
catapparel_Ratings48


catapparel_noReviews <- scrape(session3) %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text
catapparel_noReviews48<-catapparel_noReviews[1:48]
catapparel_noReviews48

Pet_Supplies <-rbind(Pet_Supplies,data.frame(category = Category,
                               name = catapparel48,
                               price = catapparel_prices48,
                               ratings = catapparel_Ratings48,
                               no_of_reviews = catapparel_noReviews48))


Pet_Supplies <- Pet_Supplies[1:100,]


Pet_Supplies


```

10 PRODUCTS

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product1 <- data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Costumes-Halloween-Christmas-Adjustable-Accessories/product-reviews/B0CCVF7GKQ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:25]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:25]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:25]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:25]

  product1 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product1
  
  

```

```{r}
library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product2 <- data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Pusheen-Embroidered-Heavyweight-Loungewear-Merchandise/product-reviews/B0C43WZTC7/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product2 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product2
  
  linkRev2 = "https://www.amazon.co.uk/Pusheen-Embroidered-Heavyweight-Loungewear-Merchandise/product-reviews/B0C43WZTC7/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
      product2 <- rbind(product2,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product2
      
       
      linkRev3 = "https://www.amazon.co.uk/Pusheen-Embroidered-Heavyweight-Loungewear-Merchandise/product-reviews/B0C43WZTC7/ref=cm_cr_getr_d_paging_btm_next_3?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
      ProductRating3 <-  ProductRating3[1:10]

      
      product2 <- rbind(product2,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product2 <- product2[1:25,]


      product2
      


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product3 <- data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Topbuti-Sweaters-Turtleneck-Valentine-Christmas/product-reviews/B0CLRHTFPL/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product3 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product3
  
linkRev2 = "https://www.amazon.co.uk/Topbuti-Sweaters-Turtleneck-Valentine-Christmas/product-reviews/B0CLRHTFPL/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
        product3 <- rbind(product3,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product3

 linkRev3 = "https://www.amazon.co.uk/Topbuti-Sweaters-Turtleneck-Valentine-Christmas/product-reviews/B0CLRHTFPL/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
        product3 <- rbind(product3,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product3 <- product3[1:25,]


      product3

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product4 <- data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Idepet-Sphynx-Cat-Shirt-Turtleneck/product-reviews/B0CG9HLRN2/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product4 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product4
  
linkRev2 = "https://www.amazon.co.uk/Idepet-Sphynx-Cat-Shirt-Turtleneck/product-reviews/B0CG9HLRN2/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
        product4 <- rbind(product4,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product4

 linkRev3 = "https://www.amazon.co.uk/Idepet-Sphynx-Cat-Shirt-Turtleneck/product-reviews/B0CG9HLRN2/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
        product4 <- rbind(product4,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product4 <- product4[1:25,]


      product4


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product5 <- data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Vampire-Halloween-Costumes-Apparel-Clothing/product-reviews/B0CC4QQ887/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product5 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product5
  
linkRev2 = "https://www.amazon.co.uk/Vampire-Halloween-Costumes-Apparel-Clothing/product-reviews/B0CC4QQ887/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
        product5 <- rbind(product5,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product5

 linkRev3 = "https://www.amazon.co.uk/Vampire-Halloween-Costumes-Apparel-Clothing/product-reviews/B0CC4QQ887/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
        product5 <- rbind(product5,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product5 <- product5[1:25,]


      product5

```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product6<- data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Hairless-Breathable-T-Shirts-Sleeveless-Strawberry/product-reviews/B085YBS1XM/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product6 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product6
  
linkRev2 = "https://www.amazon.co.uk/Hairless-Breathable-T-Shirts-Sleeveless-Strawberry/product-reviews/B085YBS1XM/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
        product6 <- rbind(product6,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product6

 linkRev3 = "https://www.amazon.co.uk/Hairless-Breathable-T-Shirts-Sleeveless-Strawberry/product-reviews/B085YBS1XM/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
        product6 <- rbind(product6,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product6 <- product6[1:25,]


      product6


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product7 <- data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/OUOBOB-Cat-Breathable-Sleeveless-Peterbald/product-reviews/B0C8HB2VLJ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product7 <- data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product7
  
linkRev2 = "https://www.amazon.co.uk/OUOBOB-Cat-Breathable-Sleeveless-Peterbald/product-reviews/B0C8HB2VLJ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
        product7 <- rbind(product7,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product7

 linkRev3 = "https://www.amazon.co.uk/OUOBOB-Cat-Breathable-Sleeveless-Peterbald/product-reviews/B0C8HB2VLJ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
        product7 <- rbind(product7,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product7 <- product7[1:25,]


      product7


```

```{r}


library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product8<- data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Hairless-Tshirts-Clothes-Pullover-T-Shirts/product-reviews/B08642J5ZQ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product8 <-data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product8
  
linkRev2 = "https://www.amazon.co.uk/Hairless-Tshirts-Clothes-Pullover-T-Shirts/product-reviews/B08642J5ZQ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
        product8 <- rbind(product8,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product8

 linkRev3 = "https://www.amazon.co.uk/Hairless-Tshirts-Clothes-Pullover-T-Shirts/product-reviews/B08642J5ZQ/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
        product8 <- rbind(product8,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product8 <- product8[1:25,]


      product8


```

```{r}



library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product9<-data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Sphynx-Clothes-Stretchy-Hairless-Apparel/product-reviews/B0BM7YRDXF/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product9<-data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product9
  
linkRev2 = "https://www.amazon.co.uk/Sphynx-Clothes-Stretchy-Hairless-Apparel/product-reviews/B0BM7YRDXF/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
        product9<- rbind(product9,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product9

 linkRev3 = "https://www.amazon.co.uk/Sphynx-Clothes-Stretchy-Hairless-Apparel/product-reviews/B0BM7YRDXF/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
        product9 <- rbind(product9,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product9 <- product9[1:25,]


      product9


```

```{r}

library(dplyr)
library(rvest)
library(polite)
library(httr)
library(selectr)

product10<-data.frame()

Category <- "Cat Apparel"

linkRev1 <- "https://www.amazon.co.uk/Turtleneck-Classic-Cable-Sweater-Apparel/product-reviews/B01N98SUI6/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber"


sessionProd1 <- bow(linkRev1, user_agent = "For Educational Purpose")

scrapeNodes <- function(selector) {
  nodes <- scrape(sessionProd1) %>%
    html_nodes(selector) %>%
    html_text(trim = TRUE)
  
  if (length(nodes) == 0) {
    warning("No data found for selector: ", selector)
    return(NA)
  } else {
    return(nodes)
  }
}

  ProductName <- scrapeNodes("h1.a-size-large.a-text-ellipsis")
  Reviewer <- scrapeNodes("span.a-profile-name")[1:10]
  Review <- scrapeNodes("span.a-size-base.review-text.review-text-content")[1:10]
  Date <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")[1:10]
  ProductRating <- scrapeNodes("span.a-icon-alt")[1:10]

  product10<-data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  )
  
  product10
  
linkRev2 = "https://www.amazon.co.uk/Turtleneck-Classic-Cable-Sweater-Apparel/product-reviews/B01N98SUI6/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=2"
  
  sessionProd2 <- bow(linkRev2,
               user_agent = "For Educational Purpose")


      Reviewer2 <- scrapeNodes("span.a-profile-name")
      Reviewer2 <- Reviewer2[1:10]

      
      Review2 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review2 <- Review2[1:10]

      
      Date2 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date2 <- Date2[1:10]

      
      ProductRating2 <- scrapeNodes("span.a-icon-alt")
      ProductRating2 <- ProductRating2[1:10]

      
        product10<- rbind(product10,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product10

 linkRev3 = "https://www.amazon.co.uk/Turtleneck-Classic-Cable-Sweater-Apparel/product-reviews/B01N98SUI6/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews&pageNumber=3"
  
  sessionProd3 <- bow(linkRev3,
               user_agent = "For Educational Purpose")


      
      Reviewer3 <- scrapeNodes("span.a-profile-name")
      Reviewer3 <- Reviewer3[1:10]

      
      Review3 <- scrapeNodes("span.a-size-base.review-text.review-text-content")
      Review3 <- Review3[1:10]

      
      Date3 <- scrapeNodes("span.a-size-base.a-color-secondary.review-date")
      Date3 <- Date3[1:10]

      
      ProductRating3 <- scrapeNodes("span.a-icon-alt")
       ProductRating3 <-  ProductRating3[1:10]

      
        product10 <- rbind(product10,data.frame(
   category = rep(Category, length(Reviewer)),
    name = ProductName,
    reviewer = Reviewer,
    review = Review,
    date = Date,
    ratings = ProductRating
  ))
      
      product10 <- product10[1:25,]


      product10



```



